---
kind: pipeline
type: docker
name: default

steps:
  - name: build-chrome
    image: node
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run pack
  - name: build-ff
    image: node
    commands:
      - npm ci
      - npm run lint
      - npm run build:ff
      - npm run pack:ff
  - name: upload-chrome
    image: plugins/s3
    settings:
      path_style: true
      endpoint: s3.dandrews.net
      bucket: faceit-elo-calculator
      access_key:
        from_secret: fec_access_key
      secret_key:
        from_secret: fec_secret_key
      source: extension_ch*.*
      target: /chrome
    depends_on:
      - build-chrome
  - name: upload-firefox
    image: plugins/s3
    settings:
      path_style: true
      endpoint: s3.dandrews.net
      bucket: faceit-elo-calculator
      access_key:
        from_secret: fec_access_key
      secret_key:
        from_secret: fec_secret_key
      source: extension_ff*.*
      target: /firefox
    depends_on:
      - build-ff
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: fec_webhook_id
      webhook_token:
        from_secret: fec_webhook_token
    depends_on:
      - upload-chrome
      - upload-firefox